name: Trigger CI job on Inter-Actief GitLab
on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Trigger CI job on Inter-Actief GitLab
      uses: appleboy/gitlab-ci-action@master
      with:
        host: "https://gitlab.ia.utwente.nl"
        token: ${{ secrets.IA_GITLAB_CI_TOKEN }}
        project_id: 153
        ref: ${{ github.ref }}
